DROP TABLE IF EXISTS [CountriesCoordinates];
CREATE TABLE [CountriesCoordinates]
(
  Country     VARCHAR(100),
  Alpha2      VARCHAR(100),
  Alpha3      VARCHAR(100),
  NumericCode INT,
  Latitude    FLOAT,
  Longitude   FLOAT
);

/*
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Afghanistan', 'AF', 'AFG', 4, 33, 33);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Albania', 'AL', 'ALB', 8, 41, 41);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Algeria', 'DZ', 'DZA', 12, 28, 28);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('American Samoa', 'AS', 'ASM', 16, -14.3333, -14.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Andorra', 'AD', 'AND', 20, 42.5, 42.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Angola', 'AO', 'AGO', 24, -12.5, -12.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Anguilla', 'AI', 'AIA', 660, 18.25, 18.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Antarctica', 'AQ', 'ATA', 10, -90, -90);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Antigua and Barbuda', 'AG', 'ATG', 28, 17.05, 17.05);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Argentina', 'AR', 'ARG', 32, -34, -34);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Armenia', 'AM', 'ARM', 51, 40, 40);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Aruba', 'AW', 'ABW', 533, 12.5, 12.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Australia', 'AU', 'AUS', 36, -27, -27);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Austria', 'AT', 'AUT', 40, 47.3333, 47.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Azerbaijan', 'AZ', 'AZE', 31, 40.5, 40.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bahamas', 'BS', 'BHS', 44, 24.25, 24.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bahrain', 'BH', 'BHR', 48, 26, 26);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bangladesh', 'BD', 'BGD', 50, 24, 24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Barbados', 'BB', 'BRB', 52, 13.1667, 13.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belarus', 'BY', 'BLR', 112, 53, 53);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belgium', 'BE', 'BEL', 56, 50.8333, 50.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belize', 'BZ', 'BLZ', 84, 17.25, 17.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Benin', 'BJ', 'BEN', 204, 9.5, 9.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bermuda', 'BM', 'BMU', 60, 32.3333, 32.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bhutan', 'BT', 'BTN', 64, 27.5, 27.5);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bolivia, Plurinational State of', 'BO', 'BOL', 68, -17, -17);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bolivia', 'BO', 'BOL', 68, -17, -17);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', 70, 44, 44);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Botswana', 'BW', 'BWA', 72, -22, -22);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bouvet Island', 'BV', 'BVT', 74, -54.4333, -54.4333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Brazil', 'BR', 'BRA', 76, -10, -10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('British Indian Ocean Territory', 'IO', 'IOT', 86, -6, -6);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Brunei Darussalam', 'BN', 'BRN', 96, 4.5, 4.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Brunei', 'BN', 'BRN', 96, 4.5, 4.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bulgaria', 'BG', 'BGR', 100, 43, 43);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Burkina Faso', 'BF', 'BFA', 854, 13, 13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Burundi', 'BI', 'BDI', 108, -3.5, -3.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cambodia', 'KH', 'KHM', 116, 13, 13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cameroon', 'CM', 'CMR', 120, 6, 6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Canada', 'CA', 'CAN', 124, 60, 60);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cape Verde', 'CV', 'CPV', 132, 16, 16);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cayman Islands', 'KY', 'CYM', 136, 19.5, 19.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Central African Republic', 'CF', 'CAF', 140, 7, 7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Chad', 'TD', 'TCD', 148, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Chile', 'CL', 'CHL', 152, -30, -30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('China', 'CN', 'CHN', 156, 35, 35);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Christmas Island', 'CX', 'CXR', 162, -10.5, -10.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK', 166, -12.5, -12.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Colombia', 'CO', 'COL', 170, 4, 4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Comoros', 'KM', 'COM', 174, -12.1667, -12.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Congo', 'CG', 'COG', 178, -1, -1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Congo, the Democratic Republic of the', 'CD', 'COD', 180, 0, 0);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cook Islands', 'CK', 'COK', 184, -21.2333, -21.2333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Costa Rica', 'CR', 'CRI', 188, 10, 10);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Côte d''Ivoire', 'CI', 'CIV', 384, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ivory Coast', 'CI', 'CIV', 384, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Croatia', 'HR', 'HRV', 191, 45.1667, 45.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cuba', 'CU', 'CUB', 192, 21.5, 21.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cyprus', 'CY', 'CYP', 196, 35, 35);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Czech Republic', 'CZ', 'CZE', 203, 49.75, 49.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Denmark', 'DK', 'DNK', 208, 56, 56);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Djibouti', 'DJ', 'DJI', 262, 11.5, 11.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Dominica', 'DM', 'DMA', 212, 15.4167, 15.4167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Dominican Republic', 'DO', 'DOM', 214, 19, 19);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ecuador', 'EC', 'ECU', 218, -2, -2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Egypt', 'EG', 'EGY', 818, 27, 27);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('El Salvador', 'SV', 'SLV', 222, 13.8333, 13.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', 226, 2, 2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Eritrea', 'ER', 'ERI', 232, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Estonia', 'EE', 'EST', 233, 59, 59);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ethiopia', 'ET', 'ETH', 231, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238, -51.75, -51.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Faroe Islands', 'FO', 'FRO', 234, 62, 62);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Fiji', 'FJ', 'FJI', 242, -18, -18);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Finland', 'FI', 'FIN', 246, 64, 64);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('France', 'FR', 'FRA', 250, 46, 46);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Guiana', 'GF', 'GUF', 254, 4, 4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Polynesia', 'PF', 'PYF', 258, -15, -15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Southern Territories', 'TF', 'ATF', 260, -43, -43);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gabon', 'GA', 'GAB', 266, -1, -1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gambia', 'GM', 'GMB', 270, 13.4667, 13.4667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Georgia', 'GE', 'GEO', 268, 42, 42);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Germany', 'DE', 'DEU', 276, 51, 51);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ghana', 'GH', 'GHA', 288, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gibraltar', 'GI', 'GIB', 292, 36.1833, 36.1833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Greece', 'GR', 'GRC', 300, 39, 39);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Greenland', 'GL', 'GRL', 304, 72, 72);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Grenada', 'GD', 'GRD', 308, 12.1167, 12.1167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guadeloupe', 'GP', 'GLP', 312, 16.25, 16.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guam', 'GU', 'GUM', 316, 13.4667, 13.4667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guatemala', 'GT', 'GTM', 320, 15.5, 15.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guernsey', 'GG', 'GGY', 831, 49.5, 49.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guinea', 'GN', 'GIN', 324, 11, 11);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guinea-Bissau', 'GW', 'GNB', 624, 12, 12);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guyana', 'GY', 'GUY', 328, 5, 5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Haiti', 'HT', 'HTI', 332, 19, 19);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', 334, -53.1, -53.1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Holy See (Vatican City State)', 'VA', 'VAT', 336, 41.9, 41.9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Honduras', 'HN', 'HND', 340, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Hong Kong', 'HK', 'HKG', 344, 22.25, 22.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Hungary', 'HU', 'HUN', 348, 47, 47);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iceland', 'IS', 'ISL', 352, 65, 65);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('India', 'IN', 'IND', 356, 20, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Indonesia', 'ID', 'IDN', 360, -5, -5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iran, Islamic Republic of', 'IR', 'IRN', 364, 32, 32);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iraq', 'IQ', 'IRQ', 368, 33, 33);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ireland', 'IE', 'IRL', 372, 53, 53);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Isle of Man', 'IM', 'IMN', 833, 54.23, 54.23);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Israel', 'IL', 'ISR', 376, 31.5, 31.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Italy', 'IT', 'ITA', 380, 42.8333, 42.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jamaica', 'JM', 'JAM', 388, 18.25, 18.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Japan', 'JP', 'JPN', 392, 36, 36);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jersey', 'JE', 'JEY', 832, 49.21, 49.21);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jordan', 'JO', 'JOR', 400, 31, 31);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kazakhstan', 'KZ', 'KAZ', 398, 48, 48);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kenya', 'KE', 'KEN', 404, 1, 1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kiribati', 'KI', 'KIR', 296, 1.4167, 1.4167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408, 40, 40);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Korea, Republic of', 'KR', 'KOR', 410, 37, 37);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('South Korea', 'KR', 'KOR', 410, 37, 37);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kuwait', 'KW', 'KWT', 414, 29.3375, 29.3375);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kyrgyzstan', 'KG', 'KGZ', 417, 41, 41);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lao People''s Democratic Republic', 'LA', 'LAO', 418, 18, 18);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Latvia', 'LV', 'LVA', 428, 57, 57);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lebanon', 'LB', 'LBN', 422, 33.8333, 33.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lesotho', 'LS', 'LSO', 426, -29.5, -29.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Liberia', 'LR', 'LBR', 430, 6.5, 6.5);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Libyan Arab Jamahiriya', 'LY', 'LBY', 434, 25, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Libya', 'LY', 'LBY', 434, 25, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Liechtenstein', 'LI', 'LIE', 438, 47.1667, 47.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lithuania', 'LT', 'LTU', 440, 56, 56);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Luxembourg', 'LU', 'LUX', 442, 49.75, 49.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Macao', 'MO', 'MAC', 446, 22.1667, 22.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', 807, 41.8333, 41.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Madagascar', 'MG', 'MDG', 450, -20, -20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malawi', 'MW', 'MWI', 454, -13.5, -13.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malaysia', 'MY', 'MYS', 458, 2.5, 2.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Maldives', 'MV', 'MDV', 462, 3.25, 3.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mali', 'ML', 'MLI', 466, 17, 17);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malta', 'MT', 'MLT', 470, 35.8333, 35.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Marshall Islands', 'MH', 'MHL', 584, 9, 9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Martinique', 'MQ', 'MTQ', 474, 14.6667, 14.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mauritania', 'MR', 'MRT', 478, 20, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mauritius', 'MU', 'MUS', 480, -20.2833, -20.2833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mayotte', 'YT', 'MYT', 175, -12.8333, -12.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mexico', 'MX', 'MEX', 484, 23, 23);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Micronesia, Federated States of', 'FM', 'FSM', 583, 6.9167, 6.9167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Moldova, Republic of', 'MD', 'MDA', 498, 47, 47);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Monaco', 'MC', 'MCO', 492, 43.7333, 43.7333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mongolia', 'MN', 'MNG', 496, 46, 46);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Montenegro', 'ME', 'MNE', 499, 42, 42);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Montserrat', 'MS', 'MSR', 500, 16.75, 16.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Morocco', 'MA', 'MAR', 504, 32, 32);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mozambique', 'MZ', 'MOZ', 508, -18.25, -18.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Myanmar', 'MM', 'MMR', 104, 22, 22);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Burma', 'MM', 'MMR', 104, 22, 22);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Namibia', 'NA', 'NAM', 516, -22, -22);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nauru', 'NR', 'NRU', 520, -0.5333, -0.5333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nepal', 'NP', 'NPL', 524, 28, 28);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Netherlands', 'NL', 'NLD', 528, 52.5, 52.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Netherlands Antilles', 'AN', 'ANT', 530, 12.25, 12.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('New Caledonia', 'NC', 'NCL', 540, -21.5, -21.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('New Zealand', 'NZ', 'NZL', 554, -41, -41);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nicaragua', 'NI', 'NIC', 558, 13, 13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Niger', 'NE', 'NER', 562, 16, 16);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nigeria', 'NG', 'NGA', 566, 10, 10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Niue', 'NU', 'NIU', 570, -19.0333, -19.0333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Norfolk Island', 'NF', 'NFK', 574, -29.0333, -29.0333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Northern Mariana Islands', 'MP', 'MNP', 580, 15.2, 15.2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Norway', 'NO', 'NOR', 578, 62, 62);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Oman', 'OM', 'OMN', 512, 21, 21);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Pakistan', 'PK', 'PAK', 586, 30, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Palau', 'PW', 'PLW', 585, 7.5, 7.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Palestinian Territory, Occupied', 'PS', 'PSE', 275, 32, 32);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Panama', 'PA', 'PAN', 591, 9, 9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Papua New Guinea', 'PG', 'PNG', 598, -6, -6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Paraguay', 'PY', 'PRY', 600, -23, -23);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Peru', 'PE', 'PER', 604, -10, -10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Philippines', 'PH', 'PHL', 608, 13, 13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Pitcairn', 'PN', 'PCN', 612, -24.7, -24.7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Poland', 'PL', 'POL', 616, 52, 52);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Portugal', 'PT', 'PRT', 620, 39.5, 39.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Puerto Rico', 'PR', 'PRI', 630, 18.25, 18.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Qatar', 'QA', 'QAT', 634, 25.5, 25.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Réunion', 'RE', 'REU', 638, -21.1, -21.1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Romania', 'RO', 'ROU', 642, 46, 46);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Russian Federation', 'RU', 'RUS', 643, 60, 60);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Russia', 'RU', 'RUS', 643, 60, 60);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Rwanda', 'RW', 'RWA', 646, -2, -2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654, -15.9333, -15.9333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', 659, 17.3333, 17.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Lucia', 'LC', 'LCA', 662, 13.8833, 13.8833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', 666, 46.8333, 46.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670, 13.25, 13.25);
-- INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Vincent & the Grenadines', 'VC', 'VCT', 670, 13.25, 13.25);
-- INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('St. Vincent and the Grenadines', 'VC', 'VCT', 670, 13.25, 13.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Samoa', 'WS', 'WSM', 882, -13.5833, -13.5833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('San Marino', 'SM', 'SMR', 674, 43.7667, 43.7667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sao Tome and Principe', 'ST', 'STP', 678, 1, 1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saudi Arabia', 'SA', 'SAU', 682, 25, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Senegal', 'SN', 'SEN', 686, 14, 14);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Serbia', 'RS', 'SRB', 688, 44, 44);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Seychelles', 'SC', 'SYC', 690, -4.5833, -4.5833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sierra Leone', 'SL', 'SLE', 694, 8.5, 8.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Singapore', 'SG', 'SGP', 702, 1.3667, 1.3667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Slovakia', 'SK', 'SVK', 703, 48.6667, 48.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Slovenia', 'SI', 'SVN', 705, 46, 46);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Solomon Islands', 'SB', 'SLB', 90, -8, -8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Somalia', 'SO', 'SOM', 706, 10, 10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('South Africa', 'ZA', 'ZAF', 710, -29, -29);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, -54.5, -54.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Spain', 'ES', 'ESP', 724, 40, 40);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sri Lanka', 'LK', 'LKA', 144, 7, 7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sudan', 'SD', 'SDN', 736, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Suriname', 'SR', 'SUR', 740, 4, 4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744, 78, 78);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Swaziland', 'SZ', 'SWZ', 748, -26.5, -26.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sweden', 'SE', 'SWE', 752, 62, 62);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Switzerland', 'CH', 'CHE', 756, 47, 47);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Syrian Arab Republic', 'SY', 'SYR', 760, 35, 35);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Taiwan, Province of China', 'TW', 'TWN', 158, 23.5, 23.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Taiwan', 'TW', 'TWN', 158, 23.5, 23.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tajikistan', 'TJ', 'TJK', 762, 39, 39);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA', 834, -6, -6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Thailand', 'TH', 'THA', 764, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Timor-Leste', 'TL', 'TLS', 626, -8.55, -8.55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Togo', 'TG', 'TGO', 768, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tokelau', 'TK', 'TKL', 772, -9, -9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tonga', 'TO', 'TON', 776, -20, -20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Trinidad and Tobago', 'TT', 'TTO', 780, 11, 11);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Trinidad & Tobago', 'TT', 'TTO', 780, 11, 11);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tunisia', 'TN', 'TUN', 788, 34, 34);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turkey', 'TR', 'TUR', 792, 39, 39);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turkmenistan', 'TM', 'TKM', 795, 40, 40);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turks and Caicos Islands', 'TC', 'TCA', 796, 21.75, 21.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tuvalu', 'TV', 'TUV', 798, -8, -8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uganda', 'UG', 'UGA', 800, 1, 1);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ukraine', 'UA', 'UKR', 804, 49, 49);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United Arab Emirates', 'AE', 'ARE', 784, 24, 24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United Kingdom', 'GB', 'GBR', 826, 54, 54);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United States', 'US', 'USA', 840, 38, 38);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI', 581, 19.2833, 19.2833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uruguay', 'UY', 'URY', 858, -33, -33);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uzbekistan', 'UZ', 'UZB', 860, 41, 41);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Vanuatu', 'VU', 'VUT', 548, -16, -16);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862, 8, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Venezuela', 'VE', 'VEN', 862, 8, 8);
--INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Viet Nam', 'VN', 'VNM', 704, 16, 16);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Vietnam', 'VN', 'VNM', 704, 16, 16);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Virgin Islands, British', 'VG', 'VGB', 92, 18.5, 18.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Virgin Islands, U.S.', 'VI', 'VIR', 850, 18.3333, 18.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Wallis and Futuna', 'WF', 'WLF', 876, -13.3, -13.3);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Western Sahara', 'EH', 'ESH', 732, 24.5, 24.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Yemen', 'YE', 'YEM', 887, 15, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Zambia', 'ZM', 'ZMB', 894, -15, -15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Zimbabwe', 'ZW', 'ZWE', 716, -20, -20);

*/



INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Albania', 'AL', 'ALB', 8, 41, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Algeria', 'DZ', 'DZA', 12, 28, 3);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('American Samoa', 'AS', 'ASM', 16, -14.3333, -170);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Andorra', 'AD', 'AND', 20, 42.5, 1.6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Angola', 'AO', 'AGO', 24, -12.5, 18.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Anguilla', 'AI', 'AIA', 660, 18.25, -63.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Antarctica', 'AQ', 'ATA', 10, -90, 0);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Antigua and Barbuda', 'AG', 'ATG', 28, 17.05, -61.8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Argentina', 'AR', 'ARG', 32, -34, -64);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Armenia', 'AM', 'ARM', 51, 40, 45);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Aruba', 'AW', 'ABW', 533, 12.5, -69.9667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Australia', 'AU', 'AUS', 36, -27, 133);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Austria', 'AT', 'AUT', 40, 47.3333, 13.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Azerbaijan', 'AZ', 'AZE', 31, 40.5, 47.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bahamas', 'BS', 'BHS', 44, 24.25, -76);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bahrain', 'BH', 'BHR', 48, 26, 50.55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bangladesh', 'BD', 'BGD', 50, 24, 90);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Barbados', 'BB', 'BRB', 52, 13.1667, -59.5333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belarus', 'BY', 'BLR', 112, 53, 28);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belgium', 'BE', 'BEL', 56, 50.8333, 4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Belize', 'BZ', 'BLZ', 84, 17.25, -88.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Benin', 'BJ', 'BEN', 204, 9.5, 2.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bermuda', 'BM', 'BMU', 60, 32.3333, -64.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bhutan', 'BT', 'BTN', 64, 27.5, 90.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bolivia, Plurinational State of', 'BO', 'BOL', 68, -17, -65);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', 70, 44, 18);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Botswana', 'BW', 'BWA', 72, -22, 24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bouvet Island', 'BV', 'BVT', 74, -54.4333, 3.4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Brazil', 'BR', 'BRA', 76, -10, -55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('British Indian Ocean Territory', 'IO', 'IOT', 86, -6, 71.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Brunei Darussalam', 'BN', 'BRN', 96, 4.5, 114.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Bulgaria', 'BG', 'BGR', 100, 43, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Burkina Faso', 'BF', 'BFA', 854, 13, -2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Burundi', 'BI', 'BDI', 108, -3.5, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cambodia', 'KH', 'KHM', 116, 13, 105);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cameroon', 'CM', 'CMR', 120, 6, 12);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Canada', 'CA', 'CAN', 124, 60, -95);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cape Verde', 'CV', 'CPV', 132, 16, -24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cayman Islands', 'KY', 'CYM', 136, 19.5, -80.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Central African Republic', 'CF', 'CAF', 140, 7, 21);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Chad', 'TD', 'TCD', 148, 15, 19);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Chile', 'CL', 'CHL', 152, -30, -71);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('China', 'CN', 'CHN', 156, 35, 105);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Christmas Island', 'CX', 'CXR', 162, -10.5, 105.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK', 166, -12.5, 96.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Colombia', 'CO', 'COL', 170, 4, -72);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Comoros', 'KM', 'COM', 174, -12.1667, 44.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Congo', 'CG', 'COG', 178, -1, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Congo, the Democratic Republic of the', 'CD', 'COD', 180, 0, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cook Islands', 'CK', 'COK', 184, -21.2333, -159.7667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Costa Rica', 'CR', 'CRI', 188, 10, -84);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Côte d''Ivoire', 'CI', 'CIV', 384, 8, -5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Croatia', 'HR', 'HRV', 191, 45.1667, 15.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cuba', 'CU', 'CUB', 192, 21.5, -80);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Cyprus', 'CY', 'CYP', 196, 35, 33);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Czech Republic', 'CZ', 'CZE', 203, 49.75, 15.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Denmark', 'DK', 'DNK', 208, 56, 10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Djibouti', 'DJ', 'DJI', 262, 11.5, 43);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Dominica', 'DM', 'DMA', 212, 15.4167, -61.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Dominican Republic', 'DO', 'DOM', 214, 19, -70.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ecuador', 'EC', 'ECU', 218, -2, -77.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Egypt', 'EG', 'EGY', 818, 27, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('El Salvador', 'SV', 'SLV', 222, 13.8333, -88.9167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', 226, 2, 10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Eritrea', 'ER', 'ERI', 232, 15, 39);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Estonia', 'EE', 'EST', 233, 59, 26);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ethiopia', 'ET', 'ETH', 231, 8, 38);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238, -51.75, -59);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Faroe Islands', 'FO', 'FRO', 234, 62, -7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Fiji', 'FJ', 'FJI', 242, -18, 175);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Finland', 'FI', 'FIN', 246, 64, 26);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('France', 'FR', 'FRA', 250, 46, 2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Guiana', 'GF', 'GUF', 254, 4, -53);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Polynesia', 'PF', 'PYF', 258, -15, -140);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('French Southern Territories', 'TF', 'ATF', 260, -43, 67);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gabon', 'GA', 'GAB', 266, -1, 11.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gambia', 'GM', 'GMB', 270, 13.4667, -16.5667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Georgia', 'GE', 'GEO', 268, 42, 43.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Germany', 'DE', 'DEU', 276, 51, 9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ghana', 'GH', 'GHA', 288, 8, -2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Gibraltar', 'GI', 'GIB', 292, 36.1833, -5.3667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Greece', 'GR', 'GRC', 300, 39, 22);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Greenland', 'GL', 'GRL', 304, 72, -40);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Grenada', 'GD', 'GRD', 308, 12.1167, -61.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guadeloupe', 'GP', 'GLP', 312, 16.25, -61.5833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guam', 'GU', 'GUM', 316, 13.4667, 144.7833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guatemala', 'GT', 'GTM', 320, 15.5, -90.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guernsey', 'GG', 'GGY', 831, 49.5, -2.56);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guinea', 'GN', 'GIN', 324, 11, -10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guinea-Bissau', 'GW', 'GNB', 624, 12, -15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Guyana', 'GY', 'GUY', 328, 5, -59);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Haiti', 'HT', 'HTI', 332, 19, -72.4167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', 334, -53.1, 72.5167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Holy See (Vatican City State)', 'VA', 'VAT', 336, 41.9, 12.45);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Honduras', 'HN', 'HND', 340, 15, -86.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Hong Kong', 'HK', 'HKG', 344, 22.25, 114.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Hungary', 'HU', 'HUN', 348, 47, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iceland', 'IS', 'ISL', 352, 65, -18);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('India', 'IN', 'IND', 356, 20, 77);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Indonesia', 'ID', 'IDN', 360, -5, 120);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iran, Islamic Republic of', 'IR', 'IRN', 364, 32, 53);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Iraq', 'IQ', 'IRQ', 368, 33, 44);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ireland', 'IE', 'IRL', 372, 53, -8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Isle of Man', 'IM', 'IMN', 833, 54.23, -4.55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Israel', 'IL', 'ISR', 376, 31.5, 34.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Italy', 'IT', 'ITA', 380, 42.8333, 12.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jamaica', 'JM', 'JAM', 388, 18.25, -77.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Japan', 'JP', 'JPN', 392, 36, 138);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jersey', 'JE', 'JEY', 832, 49.21, -2.13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Jordan', 'JO', 'JOR', 400, 31, 36);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kazakhstan', 'KZ', 'KAZ', 398, 48, 68);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kenya', 'KE', 'KEN', 404, 1, 38);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kiribati', 'KI', 'KIR', 296, 1.4167, 173);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408, 40, 127);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Korea, Republic of', 'KR', 'KOR', 410, 37, 127.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kuwait', 'KW', 'KWT', 414, 29.3375, 47.6581);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Kyrgyzstan', 'KG', 'KGZ', 417, 41, 75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lao People''s Democratic Republic', 'LA', 'LAO', 418, 18, 105);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Latvia', 'LV', 'LVA', 428, 57, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lebanon', 'LB', 'LBN', 422, 33.8333, 35.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lesotho', 'LS', 'LSO', 426, -29.5, 28.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Liberia', 'LR', 'LBR', 430, 6.5, -9.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Libyan Arab Jamahiriya', 'LY', 'LBY', 434, 25, 17);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Liechtenstein', 'LI', 'LIE', 438, 47.1667, 9.5333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Lithuania', 'LT', 'LTU', 440, 56, 24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Luxembourg', 'LU', 'LUX', 442, 49.75, 6.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Macao', 'MO', 'MAC', 446, 22.1667, 113.55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', 807, 41.8333, 22);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Madagascar', 'MG', 'MDG', 450, -20, 47);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malawi', 'MW', 'MWI', 454, -13.5, 34);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malaysia', 'MY', 'MYS', 458, 2.5, 112.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Maldives', 'MV', 'MDV', 462, 3.25, 73);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mali', 'ML', 'MLI', 466, 17, -4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Malta', 'MT', 'MLT', 470, 35.8333, 14.5833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Marshall Islands', 'MH', 'MHL', 584, 9, 168);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Martinique', 'MQ', 'MTQ', 474, 14.6667, -61);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mauritania', 'MR', 'MRT', 478, 20, -12);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mauritius', 'MU', 'MUS', 480, -20.2833, 57.55);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mayotte', 'YT', 'MYT', 175, -12.8333, 45.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mexico', 'MX', 'MEX', 484, 23, -102);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Micronesia, Federated States of', 'FM', 'FSM', 583, 6.9167, 158.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Moldova, Republic of', 'MD', 'MDA', 498, 47, 29);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Monaco', 'MC', 'MCO', 492, 43.7333, 7.4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mongolia', 'MN', 'MNG', 496, 46, 105);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Montenegro', 'ME', 'MNE', 499, 42, 19);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Montserrat', 'MS', 'MSR', 500, 16.75, -62.2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Morocco', 'MA', 'MAR', 504, 32, -5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Mozambique', 'MZ', 'MOZ', 508, -18.25, 35);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Myanmar', 'MM', 'MMR', 104, 22, 98);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Namibia', 'NA', 'NAM', 516, -22, 17);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nauru', 'NR', 'NRU', 520, -0.5333, 166.9167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nepal', 'NP', 'NPL', 524, 28, 84);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Netherlands', 'NL', 'NLD', 528, 52.5, 5.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Netherlands Antilles', 'AN', 'ANT', 530, 12.25, -68.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('New Caledonia', 'NC', 'NCL', 540, -21.5, 165.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('New Zealand', 'NZ', 'NZL', 554, -41, 174);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nicaragua', 'NI', 'NIC', 558, 13, -85);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Niger', 'NE', 'NER', 562, 16, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Nigeria', 'NG', 'NGA', 566, 10, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Niue', 'NU', 'NIU', 570, -19.0333, -169.8667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Norfolk Island', 'NF', 'NFK', 574, -29.0333, 167.95);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Northern Mariana Islands', 'MP', 'MNP', 580, 15.2, 145.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Norway', 'NO', 'NOR', 578, 62, 10);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Oman', 'OM', 'OMN', 512, 21, 57);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Pakistan', 'PK', 'PAK', 586, 30, 70);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Palau', 'PW', 'PLW', 585, 7.5, 134.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Palestinian Territory, Occupied', 'PS', 'PSE', 275, 32, 35.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Panama', 'PA', 'PAN', 591, 9, -80);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Papua New Guinea', 'PG', 'PNG', 598, -6, 147);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Paraguay', 'PY', 'PRY', 600, -23, -58);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Peru', 'PE', 'PER', 604, -10, -76);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Philippines', 'PH', 'PHL', 608, 13, 122);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Pitcairn', 'PN', 'PCN', 612, -24.7, -127.4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Poland', 'PL', 'POL', 616, 52, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Portugal', 'PT', 'PRT', 620, 39.5, -8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Puerto Rico', 'PR', 'PRI', 630, 18.25, -66.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Qatar', 'QA', 'QAT', 634, 25.5, 51.25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Réunion', 'RE', 'REU', 638, -21.1, 55.6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Romania', 'RO', 'ROU', 642, 46, 25);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Russian Federation', 'RU', 'RUS', 643, 60, 100);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Rwanda', 'RW', 'RWA', 646, -2, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654, -15.9333, -5.7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', 659, 17.3333, -62.75);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Lucia', 'LC', 'LCA', 662, 13.8833, -61.1333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', 666, 46.8333, -56.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670, 13.25, -61.2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Samoa', 'WS', 'WSM', 882, -13.5833, -172.3333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('San Marino', 'SM', 'SMR', 674, 43.7667, 12.4167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sao Tome and Principe', 'ST', 'STP', 678, 1, 7);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Saudi Arabia', 'SA', 'SAU', 682, 25, 45);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Senegal', 'SN', 'SEN', 686, 14, -14);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Serbia', 'RS', 'SRB', 688, 44, 21);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Seychelles', 'SC', 'SYC', 690, -4.5833, 55.6667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sierra Leone', 'SL', 'SLE', 694, 8.5, -11.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Singapore', 'SG', 'SGP', 702, 1.3667, 103.8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Slovakia', 'SK', 'SVK', 703, 48.6667, 19.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Slovenia', 'SI', 'SVN', 705, 46, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Solomon Islands', 'SB', 'SLB', 90, -8, 159);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Somalia', 'SO', 'SOM', 706, 10, 49);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('South Africa', 'ZA', 'ZAF', 710, -29, 24);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, -54.5, -37);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Spain', 'ES', 'ESP', 724, 40, -4);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sri Lanka', 'LK', 'LKA', 144, 7, 81);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sudan', 'SD', 'SDN', 736, 15, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Suriname', 'SR', 'SUR', 740, 4, -56);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744, 78, 20);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Swaziland', 'SZ', 'SWZ', 748, -26.5, 31.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Sweden', 'SE', 'SWE', 752, 62, 15);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Switzerland', 'CH', 'CHE', 756, 47, 8);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Syrian Arab Republic', 'SY', 'SYR', 760, 35, 38);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Taiwan, Province of China', 'TW', 'TWN', 158, 23.5, 121);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tajikistan', 'TJ', 'TJK', 762, 39, 71);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA', 834, -6, 35);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Thailand', 'TH', 'THA', 764, 15, 100);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Timor-Leste', 'TL', 'TLS', 626, -8.55, 125.5167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Togo', 'TG', 'TGO', 768, 8, 1.1667);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tokelau', 'TK', 'TKL', 772, -9, -172);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tonga', 'TO', 'TON', 776, -20, -175);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Trinidad and Tobago', 'TT', 'TTO', 780, 11, -61);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tunisia', 'TN', 'TUN', 788, 34, 9);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turkey', 'TR', 'TUR', 792, 39, 35);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turkmenistan', 'TM', 'TKM', 795, 40, 60);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Turks and Caicos Islands', 'TC', 'TCA', 796, 21.75, -71.5833);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Tuvalu', 'TV', 'TUV', 798, -8, 178);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uganda', 'UG', 'UGA', 800, 1, 32);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Ukraine', 'UA', 'UKR', 804, 49, 32);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United Arab Emirates', 'AE', 'ARE', 784, 24, 54);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United Kingdom', 'GB', 'GBR', 826, 54, -2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United States', 'US', 'USA', 840, 38, -97);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI', 581, 19.2833, 166.6);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uruguay', 'UY', 'URY', 858, -33, -56);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Uzbekistan', 'UZ', 'UZB', 860, 41, 64);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Vanuatu', 'VU', 'VUT', 548, -16, 167);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862, 8, -66);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Viet Nam', 'VN', 'VNM', 704, 16, 106);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Virgin Islands, British', 'VG', 'VGB', 92, 18.5, -64.5);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Virgin Islands, U.S.', 'VI', 'VIR', 850, 18.3333, -64.8333);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Wallis and Futuna', 'WF', 'WLF', 876, -13.3, -176.2);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Western Sahara', 'EH', 'ESH', 732, 24.5, -13);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Yemen', 'YE', 'YEM', 887, 15, 48);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Zambia', 'ZM', 'ZMB', 894, -15, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Zimbabwe', 'ZW', 'ZWE', 716, -20, 30);
INSERT INTO [CountriesCoordinates] (Country, Alpha2, Alpha3, NumericCode, Latitude, Longitude) VALUES ('Afghanistan', 'AF', 'AFG', 4, 33, 65);


