CREATE TABLE CountryNames_EN_BR
(
  ID      CHAR(2)     NOT NULL,
  NAME_EN VARCHAR(64) NOT NULL,
  NAME_BR VARCHAR(64) NOT NULL
);
INSERT INTO CountryNames_EN_BR(ID, NAME_EN, NAME_BR) 
VALUES 
('AC', 'Ascension Island', 'Ilha de Ascensão'),
('AD', 'Andorra', 'Andorra'),
('AE', 'United Arab Emirates', 'Emirados Árabes Unidos'),
('AF', 'Afghanistan', 'Afeganistão'),
('AG', 'Antigua & Barbuda', 'Antígua e Barbuda'),
('AI', 'Anguilla', 'Anguilla'),
('AL', 'Albania', 'Albânia'),
('AM', 'Armenia', 'Armênia'),
('AO', 'Angola', 'Angola'),
('AQ', 'Antarctica', 'Antártida'),
('AR', 'Argentina', 'Argentina'),
('AS', 'American Samoa', 'Samoa Americana'),
('AT', 'Austria', 'Áustria'),
('AU', 'Australia', 'Austrália'),
('AW', 'Aruba', 'Aruba'),
('AX', 'Åland Islands', 'Ilhas Åland'),
('AZ', 'Azerbaijan', 'Azerbaijão'),
('BA', 'Bosnia & Herzegovina', 'Bósnia e Herzegovina'),
('BB', 'Barbados', 'Barbados'),
('BD', 'Bangladesh', 'Bangladesh'),
('BE', 'Belgium', 'Bélgica'),
('BF', 'Burkina Faso', 'Burquina Faso'),
('BG', 'Bulgaria', 'Bulgária'),
('BH', 'Bahrain', 'Bahrein'),
('BI', 'Burundi', 'Burundi'),
('BJ', 'Benin', 'Benin'),
('BL', 'St. Barthélemy', 'São Bartolomeu'),
('BM', 'Bermuda', 'Bermudas'),
('BN', 'Brunei', 'Brunei'),
('BO', 'Bolivia', 'Bolívia'),
('BQ', 'Caribbean Netherlands', 'Países Baixos Caribenhos'),
('BR', 'Brazil', 'Brasil'),
('BS', 'Bahamas', 'Bahamas'),
('BT', 'Bhutan', 'Butão'),
('BW', 'Botswana', 'Botsuana'),
('BY', 'Belarus', 'Bielorrússia'),
('BZ', 'Belize', 'Belize'),
('CA', 'Canada', 'Canadá'),
('CC', 'Cocos (Keeling) Islands', 'Ilhas Cocos (Keeling)'),
('CD', 'Congo - Kinshasa', 'Congo - Kinshasa'),
('CF', 'Central African Republic', 'República Centro-Africana'),
('CG', 'Congo - Brazzaville', 'Congo - Brazzaville'),
('CH', 'Switzerland', 'Suíça'),
('CI', 'Côte d’Ivoire', 'Costa do Marfim'),
('CK', 'Cook Islands', 'Ilhas Cook'),
('CL', 'Chile', 'Chile'),
('CM', 'Cameroon', 'República dos Camarões'),
('CN', 'China', 'China'),
('CO', 'Colombia', 'Colômbia'),
('CR', 'Costa Rica', 'Costa Rica'),
('CU', 'Cuba', 'Cuba'),
('CV', 'Cape Verde', 'Cabo Verde'),
('CW', 'Curaçao', 'Curaçao'),
('CX', 'Christmas Island', 'Ilha Christmas'),
('CY', 'Cyprus', 'Chipre'),
('CZ', 'Czechia', 'Tchéquia'),
('DE', 'Germany', 'Alemanha'),
('DG', 'Diego Garcia', 'Diego Garcia'),
('DJ', 'Djibouti', 'Djibuti'),
('DK', 'Denmark', 'Dinamarca'),
('DM', 'Dominica', 'Dominica'),
('DO', 'Dominican Republic', 'República Dominicana'),
('DZ', 'Algeria', 'Argélia'),
('EA', 'Ceuta & Melilla', 'Ceuta e Melilha'),
('EC', 'Ecuador', 'Equador'),
('EE', 'Estonia', 'Estônia'),
('EG', 'Egypt', 'Egito'),
('EH', 'Western Sahara', 'Saara Ocidental'),
('ER', 'Eritrea', 'Eritreia'),
('ES', 'Spain', 'Espanha'),
('ET', 'Ethiopia', 'Etiópia'),
('EZ', 'Eurozone', 'Eurozone'),
('FI', 'Finland', 'Finlândia'),
('FJ', 'Fiji', 'Fiji'),
('FK', 'Falkland Islands', 'Ilhas Malvinas'),
('FM', 'Micronesia', 'Micronésia'),
('FO', 'Faroe Islands', 'Ilhas Faroe'),
('FR', 'France', 'França'),
('GA', 'Gabon', 'Gabão'),
('GB', 'United Kingdom', 'Reino Unido'),
('GD', 'Grenada', 'Granada'),
('GE', 'Georgia', 'Geórgia'),
('GF', 'French Guiana', 'Guiana Francesa'),
('GG', 'Guernsey', 'Guernsey'),
('GH', 'Ghana', 'Gana'),
('GI', 'Gibraltar', 'Gibraltar'),
('GL', 'Greenland', 'Groenlândia'),
('GM', 'Gambia', 'Gâmbia'),
('GN', 'Guinea', 'Guiné'),
('GP', 'Guadeloupe', 'Guadalupe'),
('GQ', 'Equatorial Guinea', 'Guiné Equatorial'),
('GR', 'Greece', 'Grécia'),
('GS', 'South Georgia & South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
('GT', 'Guatemala', 'Guatemala'),
('GU', 'Guam', 'Guam'),
('GW', 'Guinea-Bissau', 'Guiné-Bissau'),
('GY', 'Guyana', 'Guiana'),
('HK', 'Hong Kong SAR China', 'Hong Kong, RAE da China'),
('HN', 'Honduras', 'Honduras'),
('HR', 'Croatia', 'Croácia'),
('HT', 'Haiti', 'Haiti'),
('HU', 'Hungary', 'Hungria'),
('IC', 'Canary Islands', 'Ilhas Canárias'),
('ID', 'Indonesia', 'Indonésia'),
('IE', 'Ireland', 'Irlanda'),
('IL', 'Israel', 'Israel'),
('IM', 'Isle of Man', 'Ilha de Man'),
('IN', 'India', 'Índia'),
('IO', 'British Indian Ocean Territory', 'Território Britânico do Oceano Índico'),
('IQ', 'Iraq', 'Iraque'),
('IR', 'Iran', 'Irã'),
('IS', 'Iceland', 'Islândia'),
('IT', 'Italy', 'Itália'),
('JE', 'Jersey', 'Jersey'),
('JM', 'Jamaica', 'Jamaica'),
('JO', 'Jordan', 'Jordânia'),
('JP', 'Japan', 'Japão'),
('KE', 'Kenya', 'Quênia'),
('KG', 'Kyrgyzstan', 'Quirguistão'),
('KH', 'Cambodia', 'Camboja'),
('KI', 'Kiribati', 'Quiribati'),
('KM', 'Comoros', 'Comores'),
('KN', 'St. Kitts & Nevis', 'São Cristóvão e Nevis'),
('KP', 'North Korea', 'Coreia do Norte'),
('KR', 'South Korea', 'Coreia do Sul'),
('KW', 'Kuwait', 'Kuwait'),
('KY', 'Cayman Islands', 'Ilhas Cayman'),
('KZ', 'Kazakhstan', 'Cazaquistão'),
('LA', 'Laos', 'Laos'),
('LB', 'Lebanon', 'Líbano'),
('LC', 'St. Lucia', 'Santa Lúcia'),
('LI', 'Liechtenstein', 'Liechtenstein'),
('LK', 'Sri Lanka', 'Sri Lanka'),
('LR', 'Liberia', 'Libéria'),
('LS', 'Lesotho', 'Lesoto'),
('LT', 'Lithuania', 'Lituânia'),
('LU', 'Luxembourg', 'Luxemburgo'),
('LV', 'Latvia', 'Letônia'),
('LY', 'Libya', 'Líbia'),
('MA', 'Morocco', 'Marrocos'),
('MC', 'Monaco', 'Mônaco'),
('MD', 'Moldova', 'Moldávia'),
('ME', 'Montenegro', 'Montenegro'),
('MF', 'St. Martin', 'São Martinho'),
('MG', 'Madagascar', 'Madagascar'),
('MH', 'Marshall Islands', 'Ilhas Marshall'),
('MK', 'Macedonia', 'Macedônia'),
('ML', 'Mali', 'Mali'),
('MM', 'Myanmar (Burma)', 'Mianmar (Birmânia)'),
('MN', 'Mongolia', 'Mongólia'),
('MO', 'Macau SAR China', 'Macau, RAE da China'),
('MP', 'Northern Mariana Islands', 'Ilhas Marianas do Norte'),
('MQ', 'Martinique', 'Martinica'),
('MR', 'Mauritania', 'Mauritânia'),
('MS', 'Montserrat', 'Montserrat'),
('MT', 'Malta', 'Malta'),
('MU', 'Mauritius', 'Maurício'),
('MV', 'Maldives', 'Maldivas'),
('MW', 'Malawi', 'Malawi'),
('MX', 'Mexico', 'México'),
('MY', 'Malaysia', 'Malásia'),
('MZ', 'Mozambique', 'Moçambique'),
('NA', 'Namibia', 'Namíbia'),
('NC', 'New Caledonia', 'Nova Caledônia'),
('NE', 'Niger', 'Níger'),
('NF', 'Norfolk Island', 'Ilha Norfolk'),
('NG', 'Nigeria', 'Nigéria'),
('NI', 'Nicaragua', 'Nicarágua'),
('NL', 'Netherlands', 'Holanda'),
('NO', 'Norway', 'Noruega'),
('NP', 'Nepal', 'Nepal'),
('NR', 'Nauru', 'Nauru'),
('NU', 'Niue', 'Niue'),
('NZ', 'New Zealand', 'Nova Zelândia'),
('OM', 'Oman', 'Omã'),
('PA', 'Panama', 'Panamá'),
('PE', 'Peru', 'Peru'),
('PF', 'French Polynesia', 'Polinésia Francesa'),
('PG', 'Papua New Guinea', 'Papua-Nova Guiné'),
('PH', 'Philippines', 'Filipinas'),
('PK', 'Pakistan', 'Paquistão'),
('PL', 'Poland', 'Polônia'),
('PM', 'St. Pierre & Miquelon', 'Saint Pierre e Miquelon'),
('PN', 'Pitcairn Islands', 'Ilhas Pitcairn'),
('PR', 'Puerto Rico', 'Porto Rico'),
('PS', 'Palestinian Territories', 'Territórios palestinos'),
('PT', 'Portugal', 'Portugal'),
('PW', 'Palau', 'Palau'),
('PY', 'Paraguay', 'Paraguai'),
('QA', 'Qatar', 'Catar'),
('RE', 'Réunion', 'Reunião'),
('RO', 'Romania', 'Romênia'),
('RS', 'Serbia', 'Sérvia'),
('RU', 'Russia', 'Rússia'),
('RW', 'Rwanda', 'Ruanda'),
('SA', 'Saudi Arabia', 'Arábia Saudita'),
('SB', 'Solomon Islands', 'Ilhas Salomão'),
('SC', 'Seychelles', 'Seicheles'),
('SD', 'Sudan', 'Sudão'),
('SE', 'Sweden', 'Suécia'),
('SG', 'Singapore', 'Cingapura'),
('SH', 'St. Helena', 'Santa Helena'),
('SI', 'Slovenia', 'Eslovênia'),
('SJ', 'Svalbard & Jan Mayen', 'Svalbard e Jan Mayen'),
('SK', 'Slovakia', 'Eslováquia'),
('SL', 'Sierra Leone', 'Serra Leoa'),
('SM', 'San Marino', 'San Marino'),
('SN', 'Senegal', 'Senegal'),
('SO', 'Somalia', 'Somália'),
('SR', 'Suriname', 'Suriname'),
('SS', 'South Sudan', 'Sudão do Sul'),
('ST', 'São Tomé & Príncipe', 'São Tomé e Príncipe'),
('SV', 'El Salvador', 'El Salvador'),
('SX', 'Sint Maarten', 'Sint Maarten'),
('SY', 'Syria', 'Síria'),
('SZ', 'Swaziland', 'Suazilândia'),
('TA', 'Tristan da Cunha', 'Tristão da Cunha'),
('TC', 'Turks & Caicos Islands', 'Ilhas Turks e Caicos'),
('TD', 'Chad', 'Chade'),
('TF', 'French Southern Territories', 'Territórios Franceses do Sul'),
('TG', 'Togo', 'Togo'),
('TH', 'Thailand', 'Tailândia'),
('TJ', 'Tajikistan', 'Tajiquistão'),
('TK', 'Tokelau', 'Tokelau'),
('TL', 'Timor-Leste', 'Timor-Leste'),
('TM', 'Turkmenistan', 'Turcomenistão'),
('TN', 'Tunisia', 'Tunísia'),
('TO', 'Tonga', 'Tonga'),
('TR', 'Turkey', 'Turquia'),
('TT', 'Trinidad & Tobago', 'Trinidad e Tobago'),
('TV', 'Tuvalu', 'Tuvalu'),
('TW', 'Taiwan', 'Taiwan'),
('TZ', 'Tanzania', 'Tanzânia'),
('UA', 'Ukraine', 'Ucrânia'),
('UG', 'Uganda', 'Uganda'),
('UM', 'U.S. Outlying Islands', 'Ilhas Menores Distantes dos EUA'),
('UN', 'United Nations', 'Nações Unidas'),
('US', 'United States', 'Estados Unidos'),
('UY', 'Uruguay', 'Uruguai'),
('UZ', 'Uzbekistan', 'Uzbequistão'),
('VA', 'Vatican City', 'Cidade do Vaticano'),
('VC', 'St. Vincent & Grenadines', 'São Vicente e Granadinas'),
('VE', 'Venezuela', 'Venezuela'),
('VG', 'British Virgin Islands', 'Ilhas Virgens Britânicas'),
('VI', 'U.S. Virgin Islands', 'Ilhas Virgens dos EUA'),
('VN', 'Vietnam', 'Vietnã'),
('VU', 'Vanuatu', 'Vanuatu'),
('WF', 'Wallis & Futuna', 'Wallis e Futuna'),
('WS', 'Samoa', 'Samoa'),
('XK', 'Kosovo', 'Kosovo'),
('YE', 'Yemen', 'Iêmen'),
('YT', 'Mayotte', 'Mayotte'),
('ZA', 'South Africa', 'África do Sul'),
('ZM', 'Zambia', 'Zâmbia'),
('ZW', 'Zimbabwe', 'Zimbábue');