CREATE PROCEDURE [dbo].[COUNTRY_CRUD]
	@COU_ID              INT          = NULL,
	@COU_NOME            VARCHAR(100) = NULL,
	@COU_NAME            VARCHAR(100) = NULL,
	@COU_NOMBRE          VARCHAR(100) = NULL,
	@COU_ISO31661NUMERIC INT          = NULL,
	@COU_ISO31661ALPHA2  CHAR(2)      = NULL,
	@COU_ISO31661ALPHA3  CHAR(3)      = NULL,
	@CRUD                VARCHAR(6)   = NULL,
	@RESULT              VARCHAR(7)   = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	SET @RESULT = ('ERROR');
	BEGIN TRY
		DECLARE @T CHAR(24) = ('TRANSACTION_COUNTRY_CRUD'); 
		BEGIN TRANSACTION @T;
		IF (@CRUD IS NOT NULL) 
		BEGIN
			DECLARE @CRUD_LIST_TABLE_ARRAY TABLE
			(   
			    CRUD_ID     INT IDENTITY,
				CRUD_NAME   VARCHAR(6),
				PRIMARY KEY (CRUD_ID),
				UNIQUE      (CRUD_NAME)
			);
			INSERT INTO @CRUD_LIST_TABLE_ARRAY(CRUD_NAME) VALUES 
					(UPPER('insert')), -- C CREATE
					(UPPER('select')), -- R READ
					(UPPER('update')), -- U UPDATE
					(UPPER('delete')); -- D DELETE
			IF ((UPPER(@CRUD)) = (SELECT (UPPER([C].[CRUD_NAME])) FROM @CRUD_LIST_TABLE_ARRAY AS [C] WHERE (UPPER([C].[CRUD_NAME])) = (UPPER(@CRUD))))
			BEGIN
				IF (@CRUD = (UPPER('insert')))
				BEGIN
					PRINT 'INSERT';
					INSERT INTO [dbo].[COUNTRY](COU_NOME, COU_NAME, COU_NOMBRE, COU_ISO31661NUMERIC, COU_ISO31661ALPHA2, COU_ISO31661ALPHA3) VALUES (@COU_NOME, @COU_NAME, @COU_NOMBRE, @COU_ISO31661NUMERIC, @COU_ISO31661ALPHA2, @COU_ISO31661ALPHA3);
					
					IF ((@COU_NOME) = (SELECT [C].[COU_NOME] FROM [dbo].[COUNTRY] AS [C] WHERE (COU_NOME) = (@COU_NOME)))
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE (COU_NOME) = (@COU_NOME);
					END
					ELSE
					BEGIN
						PRINT ('ERRO INSERT COD.0004');
						RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO INSERT COD.0004') WITH LOG;
					END;
				END
				ELSE IF (@CRUD = (UPPER('select')))
				BEGIN
					PRINT 'SELECT';
					IF (@COU_ID IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_ID]) = (@COU_ID);
					END
					ELSE IF (@COU_NOME IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_NOME]) = (@COU_NOME);
					END
					ELSE IF (@COU_NAME IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_NAME]) = (@COU_NAME);
					END
					ELSE IF (@COU_NOMBRE IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_NOMBRE]) = (@COU_NOMBRE);
					END
					ELSE IF (@COU_ISO31661NUMERIC IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_ISO31661NUMERIC]) = (@COU_ISO31661NUMERIC);
					END
					ELSE IF (@COU_ISO31661ALPHA2 IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_ISO31661ALPHA2]) = (@COU_ISO31661ALPHA2);
					END
					ELSE IF (@COU_ISO31661ALPHA3 IS NOT NULL)
					BEGIN
						SELECT [C].[COU_ID], [C].[COU_NOME], [C].[COU_NAME], [C].[COU_NOMBRE], [C].[COU_ISO31661NUMERIC], [C].[COU_ISO31661ALPHA2], [C].[COU_ISO31661ALPHA3] FROM  [dbo].[COUNTRY] AS [C] WHERE ([C].[COU_ISO31661ALPHA3]) = (@COU_ISO31661ALPHA3);
					END
					ELSE
					BEGIN
						PRINT ('ERRO SELECT COD.0005');
						RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO SELECT COD.0005') WITH LOG;
					END;
				END
				ELSE IF (@CRUD = (UPPER('update')))
				BEGIN
					PRINT 'UPDATE';
				END
				ELSE IF (@CRUD = (UPPER('delete')))
				BEGIN
					PRINT 'DELETE';
				END
				ELSE 
				BEGIN
					PRINT ('ERRO SELECT @@CRUD COD.0008');
					RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO SELECT @@CRUD COD.0008') WITH LOG;
				END;
				IF ((@@TRANCOUNT) >= (1)) 
				BEGIN
					PRINT 'COMMIT TRANSACTION @T [  ]';
						COMMIT TRANSACTION @T;
					PRINT 'COMMIT TRANSACTION @T [OK]';
					SET @RESULT = (UPPER('SUCESSO'));
					RETURN (0);
				END
				ELSE
				BEGIN
					PRINT ('ERRO CRUD TRANSACTION @T COD.0009');
					RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD TRANSACTION @T COD.0009') WITH LOG;
				END;			
			END
			ELSE
			BEGIN
				PRINT ('ERRO CRUD @CRUD_LIST_TABLE_ARRAY COD.0003');
				RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD @CRUD_LIST_TABLE_ARRAY COD.0003') WITH LOG;
			END;
		END
		ELSE 
		BEGIN
			PRINT ('ERRO CRUD SELECT (NULL) COD.0002');
			RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD SELECT (NULL) COD.0002') WITH LOG;
			/*
				RAISERROR ('dbo].[COUNTRY_CRUD]Y', 16, 1) WITH LOG;  
			*/
		END;
	END TRY
	BEGIN CATCH
		PRINT 'ERROR [  ] COD.0001';
		IF ((@@TRANCOUNT) >= (1)) 
		BEGIN
			PRINT 'ROLLBACK TRANSACTION @T [  ]';
				ROLLBACK TRANSACTION @T;
			PRINT 'ROLLBACK TRANSACTION @T [OK]';
		END;
		PRINT 'ERROR [OK] COD.0001';
		RETURN (1);
	END CATCH;
	/*
		--SELECT CAST('FALSE' as bit) AS [FALSE]  -- RETURN 0 SUCESS
		--SELECT CAST('TRUE'  as bit) AS [TRUE]   -- RETURN 1 ERROR
	*/
END;