CREATE PROCEDURE [dbo].[CRUD_LIST_ARRAY]
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
			DECLARE @T CHAR(27) = ('TRANSACTION_CRUD_LIST_ARRAY'); 
			BEGIN TRANSACTION @T;	
        		DECLARE @CRUD_LIST_TABLE_ARRAY TABLE
				(
					CRUD_ID     INT IDENTITY,
					CRUD_NAME   VARCHAR(6),
					PRIMARY KEY (CRUD_ID),
					UNIQUE      (CRUD_NAME)
				);
				INSERT INTO @CRUD_LIST_TABLE_ARRAY(CRUD_NAME)
				VALUES
				(UPPER('INSERT')), -- C CREATE
				(UPPER('SELECT')), -- R READ
				(UPPER('UPDATE')), -- U UPDATE
				(UPPER('DELETE')); -- D DELETE
				--SELECT C.CRUD_ID, C.CRUD_NAME FROM @CRUD_LIST_TABLE_ARRAY  AS C WHERE ((C.CRUD_ID) >= (0));
				--SELECT COUNT(C.CRUD_NAME) AS [CRUD_COUNT] FROM @CRUD_LIST_TABLE_ARRAY AS C WHERE ((C.CRUD_ID) >= (0));
				--DECLARE @CRUD_COUNT INT = (SELECT COUNT(C.CRUD_NAME) AS [CRUD_COUNT] FROM @CRUD_LIST_TABLE_ARRAY AS C WHERE ((C.CRUD_ID) >= (0)));
				IF ((@@TRANCOUNT) > (0)) 
				BEGIN
					 COMMIT TRANSACTION @T;
				END;
				RETURN 0;
	END TRY
	BEGIN CATCH
		IF ((@@TRANCOUNT) > (0)) 
		BEGIN
			ROLLBACK TRANSACTION @T;
		END;
		RETURN (1);
	END CATCH; 
END;
