CREATE PROCEDURE [dbo].[CRUD_LIST_ARRAY_ONLY]
@RESULT VARCHAR(7) = NULL OUTPUT 
AS
BEGIN
	SET NOCOUNT ON;
	SET @RESULT = ('ERROR');
	BEGIN TRY
			DECLARE @TRANSACTION_CRUD_LIST_ARRAY_ONLY CHAR(32) = ('TRANSACTION_CRUD_LIST_ARRAY_ONLY'); 
			BEGIN TRANSACTION @TRANSACTION_CRUD_LIST_ARRAY_ONLY;	
				--CREATE [#CRUD_LIST_ARRAY_ONLY] TABLE
				DROP TABLE IF EXISTS [dbo].[##CRUD_LIST_ARRAY_ONLY];
				CREATE TABLE [dbo].[##CRUD_LIST_ARRAY_ONLY]
				(
					CRUD_ID     INT IDENTITY PRIMARY KEY CHECK ( CRUD_ID >=(1) AND CRUD_ID <=(4)),
					CRUD_NAME   VARCHAR(6) UNIQUE
				);
				INSERT INTO [dbo].[##CRUD_LIST_ARRAY_ONLY](CRUD_NAME)
				VALUES
				(UPPER('INSERT')), -- C CREATE
				(UPPER('SELECT')), -- R READ
				(UPPER('UPDATE')), -- U UPDATE
				(UPPER('DELETE')); -- D DELETE
				IF ((@@TRANCOUNT) >= (1)) 
				BEGIN
					 COMMIT TRANSACTION @TRANSACTION_CRUD_LIST_ARRAY_ONLY;
					 SET @RESULT = (UPPER('SUCESSO'));
				END;
				RETURN (0);
	END TRY
	BEGIN CATCH
		IF ((@@TRANCOUNT) >= (1)) 
		BEGIN
			ROLLBACK TRANSACTION @TRANSACTION_CRUD_LIST_ARRAY_ONLY;
		END;
		RETURN (1);
	END CATCH; 
END;