CREATE PROCEDURE [dbo].[COUNTRY_CRUD]
	@COU_ID              INT          = NULL,
	@COU_NOME            VARCHAR(100) = NULL,
	@COU_NAME            VARCHAR(100) = NULL,
	@COU_NOMBRE          VARCHAR(100) = NULL,
	@COU_ISO31661NUMERIC INT          = NULL,
	@COU_ISO31661ALPHA2  CHAR(2)      = NULL,
	@COU_ISO31661ALPHA3  CHAR(3)      = NULL,
	@CRUD                VARCHAR(6)   = NULL,
	@RESULT              VARCHAR(7)   = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	SET @RESULT = ('ERROR');
	BEGIN TRY
		DECLARE @T CHAR(24) = ('TRANSACTION_COUNTRY_CRUD'); 
		BEGIN TRANSACTION @T;
		IF (@CRUD IS NOT NULL) 
		BEGIN
			DECLARE @CRUD_LIST_TABLE_ARRAY TABLE
			(   
			    CRUD_ID     INT IDENTITY,
				CRUD_NAME   VARCHAR(6),
				PRIMARY KEY (CRUD_ID),
				UNIQUE      (CRUD_NAME)
			);
			INSERT INTO @CRUD_LIST_TABLE_ARRAY(CRUD_NAME) VALUES 
					(UPPER('insert')), -- C CREATE
					(UPPER('select')), -- R READ
					(UPPER('update')), -- U UPDATE
					(UPPER('delete')); -- D DELETE
			IF ((UPPER(@CRUD)) = (SELECT (UPPER([C].[CRUD_NAME])) FROM @CRUD_LIST_TABLE_ARRAY AS [C] WHERE (UPPER([C].[CRUD_NAME])) = (UPPER(@CRUD))))
			BEGIN
				DECLARE @IDENT_CURRENT INT = IDENT_CURRENT('[dbo].[COUNTRY]');
				PRINT (('@IDENT_CURRENT : ') + (CONVERT(VARCHAR, @IDENT_CURRENT)));	
				SELECT @IDENT_CURRENT AS [@IDENT_CURRENT];

				IF (@CRUD = (UPPER('insert')))
				BEGIN
					PRINT 'INSERT';
				END
				ELSE IF (@CRUD = (UPPER('select')))
				BEGIN
					PRINT 'SELECT';
				END
				ELSE IF (@CRUD = (UPPER('update')))
				BEGIN
					PRINT 'UPDATE';
				END
				ELSE IF (@CRUD = (UPPER('delete')))
				BEGIN
					PRINT 'DELETE';
				END
				ELSE 
				BEGIN
					PRINT ('ERRO SELECT @@CRUD');
					RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO SELECT @@CRUD)') WITH LOG;
				END;
				IF ((@@TRANCOUNT) >= (1)) 
				BEGIN
					PRINT 'ROLLBACK TRANSACTION @T [  ]';
						COMMIT TRANSACTION @T;
					PRINT 'ROLLBACK TRANSACTION @T [OK]';
					SET @RESULT = (UPPER('SUCESSO'));
					RETURN (0);
				END
				ELSE
				BEGIN
					PRINT ('ERRO CRUD TRANSACTION @T');
					RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD TRANSACTION @T)') WITH LOG;
				END;			
			END
			ELSE
			BEGIN
				PRINT ('ERRO CRUD @CRUD_LIST_TABLE_ARRAY');
				RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD @CRUD_LIST_TABLE_ARRAY)') WITH LOG;
			END;
		END
		ELSE 
		BEGIN
			PRINT ('ERRO CRUD SELECT (NULL)');
			RAISERROR (15600,-1,-1, '[dbo].[COUNTRY_CRUD] - ERRO CRUD SELECT (NULL)') WITH LOG;
			/*
				RAISERROR ('dbo].[COUNTRY_CRUD]Y', 16, 1) WITH LOG;  
			*/
		END;
	END TRY
	BEGIN CATCH
		PRINT 'ERROR [  ]';
		IF ((@@TRANCOUNT) >= (1)) 
		BEGIN
			PRINT 'ROLLBACK TRANSACTION @T [  ]';
				ROLLBACK TRANSACTION @T;
			PRINT 'ROLLBACK TRANSACTION @T [OK]';
		END;
		PRINT 'ERROR [OK]';
		RETURN (1);
	END CATCH;
	/*
		--SELECT CAST('FALSE' as bit) AS [FALSE]  -- RETURN 0 SUCESS
		--SELECT CAST('TRUE'  as bit) AS [TRUE]   -- RETURN 1 ERROR
	*/
END;

