CREATE PROCEDURE [dbo].[COUNTRY_CRUD]
	@COU_ID              INT          = NULL,
	@COU_NOME            VARCHAR(100) = NULL,
	@COU_NAME            VARCHAR(100) = NULL,
	@COU_NOMBRE          VARCHAR(100) = NULL,
	@COU_ISO31661NUMERIC INT          = NULL,
	@COU_ISO31661ALPHA2  CHAR(2)      = NULL,
	@COU_ISO31661ALPHA3  CHAR(3)      = NULL,
	@CRUD                VARCHAR(6)   = NULL,
	@RESULT              VARCHAR(7)   = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		DECLARE @T CHAR(24) = ('TRANSACTION_COUNTRY_CRUD'); 
		IF(@CRUD IS NULL)
		BEGIN
			PRINT ('ERRO CRUD SELECT (NULL)');
			SET @RESULT = (UPPER('ERROR'));
			RETURN(1);
		END;
		DECLARE @CRUD_LIST_TABLE_ARRAY TABLE
		(
			CRUD_ID     INT IDENTITY,
			CRUD_NAME   VARCHAR(6),
			PRIMARY KEY (CRUD_ID),
			UNIQUE      (CRUD_NAME)
		);
		INSERT INTO @CRUD_LIST_TABLE_ARRAY(CRUD_NAME)
		VALUES
		(UPPER('INSERT')), -- C CREATE
		(UPPER('SELECT')), -- R READ
		(UPPER('UPDATE')), -- U UPDATE
		(UPPER('DELETE')); -- D DELETE



		DECLARE @IDENT_CURRENT INT = IDENT_CURRENT('[dbo].[COUNTRY]');
		PRINT (('@IDENT_CURRENT : ') + (CONVERT(VARCHAR, @IDENT_CURRENT)));	
		SELECT @IDENT_CURRENT AS [@IDENT_CURRENT];

		BEGIN TRANSACTION @T;		
			IF ((@@TRANCOUNT) > (0)) 
			BEGIN
				 COMMIT TRANSACTION @T;
				 SET @RESULT = (UPPER('SUCESSO'));
			END;
		RETURN (0);
	END TRY
	BEGIN CATCH
		PRINT 'ERROR [  ]';
		SET @RESULT = (UPPER('ERROR'));
		IF ((@@TRANCOUNT) > (0)) 
		BEGIN
			PRINT 'ROLLBACK TRANSACTION @T [  ]';
			ROLLBACK TRANSACTION @T;
			PRINT 'ROLLBACK TRANSACTION @T [OK]';
		END;
		PRINT 'ERROR [OK]';
		RETURN (1);
	END CATCH;
END;
--SELECT CAST('FALSE' as bit) AS [FALSE]  -- RETURN 0 SUCESS
--SELECT CAST('TRUE'  as bit) AS [TRUE]   -- RETURN 1 ERROR
