PRINT '|Add COUNTRYS_FLAGS [  ]';
PRINT '|$(DataSource)$(COUNTRYS_FLAGS)';

-- FIELD TABLES
DECLARE @COU_ID             INT;
DECLARE @COF_FILE_BYTE      VARBINARY(MAX);
DECLARE @COF_FILE_NAME      VARCHAR (100);
DECLARE @COF_FILE_HASH_SHA1 VARCHAR (50);
DECLARE @COF_FILE_HASH_MD5  VARCHAR (50);


-- FLAGS PNG
DECLARE @COUNT_16x_Error	 INT = 0;
DECLARE @COUNT_16x_Sucess	 INT = 0;

DECLARE @COUNT_24x_Error	 INT = 0;
DECLARE @COUNT_24x_Sucess	 INT = 0;

DECLARE @COUNT_32x_Error	 INT = 0;
DECLARE @COUNT_32x_Sucess	 INT = 0;

DECLARE @COUNT_48x_Error	 INT = 0;
DECLARE @COUNT_48x_Sucess	 INT = 0;

DECLARE @COUNT_64x_Error	 INT = 0;
DECLARE @COUNT_64x_Sucess	 INT = 0;

DECLARE @COUNT_100x_Error	 INT = 0;
DECLARE @COUNT_100x_Sucess	 INT = 0;

DECLARE @COUNT_128x_Error	 INT = 0;
DECLARE @COUNT_128x_Sucess	 INT = 0;

DECLARE @COUNT_250x_Error	 INT = 0;
DECLARE @COUNT_250x_Sucess	 INT = 0;

DECLARE @COUNT_1000x_Error	 INT = 0;
DECLARE @COUNT_1000x_Sucess	 INT = 0;

-- SQL COMMANDS 
DECLARE @SQL VARCHAR(1000);

-- FILE NAME
DECLARE @FILE                VARCHAR(1000);

-- PATCH FULL
DECLARE @FILE_PATCH          VARCHAR(1000);

-- FLAGS COD COUNTRYS
DECLARE @COU_ISO31661_ALPHA2 CHAR(2);

--  CURSOR NAME COUNTRYS
DECLARE @COUNTRYS_CURSOR AS  CURSOR;

-- SET CURSOR COUNTRYS
SET @COUNTRYS_CURSOR = CURSOR FOR (SELECT [C].[COU_ISO31661_ALPHA2] FROM [COUNTRYS] [C]);

-- OPEN CURSOR COUNTRYS
OPEN @COUNTRYS_CURSOR;

-- FILL CURSOR COUNTRYS
FETCH NEXT FROM @COUNTRYS_CURSOR INTO @COU_ISO31661_ALPHA2;

-- WHILE NEXT ITEM CURSOR
WHILE (@@FETCH_STATUS = 0)
	BEGIN

		-- SET FIELD @COU_ID
		SET @COU_ID = (SELECT [C].[COU_ID] FROM [COUNTRYS] [C] WHERE [C].[COU_ISO31661_ALPHA2] = @COU_ISO31661_ALPHA2);

		--  CURSOR SIZE FLAGS
		DECLARE @SIZE_PATCH INT;

		--  CURSOR NAME FLAGS
		DECLARE @COUNTRYS_FLAGS AS  CURSOR;

		-- SET CURSOR FLAGS
		SET @COUNTRYS_FLAGS = CURSOR FOR (SELECT [PF].[SIZE_PATCH] FROM [dbo].[#FLAGS_PATCH] AS [PF]);

		-- OPEN CURSOR FLAGS
		OPEN @COUNTRYS_FLAGS;
		
		-- FETCH CURSOR FLAGS
		FETCH NEXT FROM @COUNTRYS_FLAGS INTO @SIZE_PATCH;

		-- WHILE NEXT ITEM CURSOR FLAGS
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			
			-- CREATE FILE NAME
			SET @FILE = LOWER(@COU_ISO31661_ALPHA2 + '.png');

			-- CREATE STRING FILE PATCH 16x 
			SET @FILE_PATCH = ('$(DefaultProjectPath)Flags\' + (CAST(@SIZE_PATCH AS VARCHAR)) + 'x\' + @FILE);
			--PRINT(@FILE + ' - ' + (CAST(@SIZE_PATCH AS VARCHAR)) );

			-- DECLARE CHECK FILE
			DECLARE @CHECK_FILE INT;

			-- CHECK FILE EXIST
			EXECUTE master.dbo.xp_fileexist @FILE_PATCH, @CHECK_FILE OUTPUT;

			IF (@CHECK_FILE = 1)
			BEGIN
				
				-- DROP TABLE [FLAG_BINARY]
				DROP TABLE IF EXISTS [FLAG_BINARY];

				SET @SQL = ('SELECT * INTO [FLAG_BINARY] FROM OPENROWSET(BULK ''');
				SET @SQL = (@SQL  +  @FILE_PATCH)
				SET @SQL = (@SQL  + ''', SINGLE_BLOB) AS [FILE];');
				EXECUTE (@SQL);
				SET @COF_FILE_BYTE      = (SELECT [F].[BulkColumn] FROM [FLAG_BINARY] AS [F]);
				SET @COF_FILE_NAME = @FILE;
				SET @COF_FILE_HASH_SHA1 = (SELECT CONVERT(VARCHAR(50), HASHBYTES('SHA1', [BulkColumn]),1) FROM [FLAG_BINARY]);
				SET @COF_FILE_HASH_MD5  = (SELECT CONVERT(VARCHAR(50), HASHBYTES('MD5', [BulkColumn]),1) FROM [FLAG_BINARY]);
				
				
				-- IF SELECT TABLE AND INSERT 
				IF (@SIZE_PATCH = 16)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_16X]
					(
						[COU_ID],
						[COF16_FILE_BYTE],
						[COF16_FILE_NAME],
						[COF16_FILE_HASH_SHA1],
						[COF16_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_16x_Sucess = @COUNT_16x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 24)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_24X]
					(
						[COU_ID],
						[COF24_FILE_BYTE],
						[COF24_FILE_NAME],
						[COF24_FILE_HASH_SHA1],
						[COF24_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_24x_Sucess = @COUNT_24x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 32)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_32X]
					(
						[COU_ID],
						[COF32_FILE_BYTE],
						[COF32_FILE_NAME],
						[COF32_FILE_HASH_SHA1],
						[COF32_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_32x_Sucess = @COUNT_32x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 48)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_48X]
					(
						[COU_ID],
						[COF48_FILE_BYTE],
						[COF48_FILE_NAME],
						[COF48_FILE_HASH_SHA1],
						[COF48_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_48x_Sucess = @COUNT_48x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 64)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_64X]
					(
						[COU_ID],
						[COF64_FILE_BYTE],
						[COF64_FILE_NAME],
						[COF64_FILE_HASH_SHA1],
						[COF64_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_64x_Sucess = @COUNT_64x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 100)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_100X]
					(
						[COU_ID],
						[COF100_FILE_BYTE],
						[COF100_FILE_NAME],
						[COF100_FILE_HASH_SHA1],
						[COF100_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_100x_Sucess = @COUNT_100x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 128)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_128X]
					(
						[COU_ID],
						[COF128_FILE_BYTE],
						[COF128_FILE_NAME],
						[COF128_FILE_HASH_SHA1],
						[COF128_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_128x_Sucess = @COUNT_128x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 250)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_250X]
					(
						[COU_ID],
						[COF250_FILE_BYTE],
						[COF250_FILE_NAME],
						[COF250_FILE_HASH_SHA1],
						[COF250_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_250x_Sucess = @COUNT_250x_Sucess + 1;
				END
				ELSE IF (@SIZE_PATCH = 1000)
				BEGIN
					INSERT INTO [COUNTRYS_FLAGS_1000X]
					(
						[COU_ID],
						[COF1000_FILE_BYTE],
						[COF1000_FILE_NAME],
						[COF1000_FILE_HASH_SHA1],
						[COF1000_FILE_HASH_MD5]
					)
					VALUES
					(
						@COU_ID,
						@COF_FILE_BYTE,
						@COF_FILE_NAME,
						@COF_FILE_HASH_SHA1,
						@COF_FILE_HASH_MD5
					);
					SET @COUNT_1000x_Sucess = @COUNT_1000x_Sucess + 1;
				END;
				DROP TABLE IF EXISTS [FLAG_BINARY];
			END
			ELSE
			BEGIN

				-- IF COUNT ERROR 
				IF (@SIZE_PATCH = 16)
				BEGIN
					SET @COUNT_16x_Error = @COUNT_16x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 24)
				BEGIN
					SET @COUNT_24x_Error = @COUNT_24x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 32)
				BEGIN
					SET @COUNT_32x_Error = @COUNT_32x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 48)
				BEGIN
					SET @COUNT_48x_Error = @COUNT_48x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 64)
				BEGIN
					SET @COUNT_64x_Error = @COUNT_64x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 100)
				BEGIN
					SET @COUNT_100x_Error = @COUNT_100x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 128)
				BEGIN
					SET @COUNT_128x_Error = @COUNT_128x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 250)
				BEGIN
					SET @COUNT_250x_Error = @COUNT_250x_Error + 1;
				END
				ELSE IF (@SIZE_PATCH = 1000)
				BEGIN
					SET @COUNT_1000x_Error = @COUNT_1000x_Error + 1;
				END;

			END;

			--NEXT CURSOR
			FETCH NEXT FROM @COUNTRYS_FLAGS INTO @SIZE_PATCH;
		END;
		-- CLOSE CURSOR 
		CLOSE @COUNTRYS_FLAGS;
		DEALLOCATE @COUNTRYS_FLAGS;

		--NEXT CURSOR
		FETCH NEXT FROM @COUNTRYS_CURSOR INTO @COU_ISO31661_ALPHA2;

	END;
PRINT '|TOTAL FLAGS 16x:   SUCESSO['  + CAST(@COUNT_16x_Sucess AS VARCHAR(10))  + '] ERROS['+ CAST(@COUNT_16x_Error AS VARCHAR(10))   + ']'
PRINT '|TOTAL FLAGS 24x:   SUCESSO['  + CAST(@COUNT_24x_Sucess AS VARCHAR(10))  + '] ERROS['+ CAST(@COUNT_24x_Error AS VARCHAR(10))   + ']'
PRINT '|TOTAL FLAGS 32x:   SUCESSO['  + CAST(@COUNT_32x_Sucess AS VARCHAR(10))  + '] ERROS['+ CAST(@COUNT_32x_Error AS VARCHAR(10))   + ']'
PRINT '|TOTAL FLAGS 48x:   SUCESSO['  + CAST(@COUNT_48x_Sucess AS VARCHAR(10))  + '] ERROS['+ CAST(@COUNT_48x_Error AS VARCHAR(10))   + ']'
PRINT '|TOTAL FLAGS 64x:   SUCESSO['  + CAST(@COUNT_64x_Sucess AS VARCHAR(10))  + '] ERROS['+ CAST(@COUNT_64x_Error AS VARCHAR(10))   + ']'
PRINT '|TOTAL FLAGS 100x:  SUCESSO['  + CAST(@COUNT_100x_Sucess AS VARCHAR(10)) + '] ERROS['+ CAST(@COUNT_100x_Error AS VARCHAR(10))  + ']'
PRINT '|TOTAL FLAGS 128x:  SUCESSO['  + CAST(@COUNT_128x_Sucess AS VARCHAR(10)) + '] ERROS['+ CAST(@COUNT_128x_Error AS VARCHAR(10))  + ']'
PRINT '|TOTAL FLAGS 250x:  SUCESSO['  + CAST(@COUNT_250x_Sucess AS VARCHAR(10)) + '] ERROS['+ CAST(@COUNT_250x_Error AS VARCHAR(10))  + ']'
PRINT '|TOTAL FLAGS 1000x: SUCESSO['  + CAST(@COUNT_100x_Sucess AS VARCHAR(10)) + '] ERROS['+ CAST(@COUNT_1000x_Error AS VARCHAR(10)) + ']'
CLOSE @COUNTRYS_CURSOR;
DEALLOCATE @COUNTRYS_CURSOR;

PRINT '|Add COUNTRYS_FLAGS [OK]';
--####################
--##                ##
--##     Version    ##
--##     2.0.0.5    ##
--##     BY  EDY    ##
--##                ##
--####################