CREATE TABLE [dbo].[COUNTRYS_FLAGS_128X] (
    [COF128_ID]             INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]                INT              NOT NULL,
    [COF128_FILE_BYTE]      VARBINARY (MAX)  NOT NULL,
    [COF128_FILE_NAME]      VARCHAR (100)    NOT NULL,
    [COF128_FILE_HASH_SHA1] VARCHAR (50)     NOT NULL,
    [COF128_FILE_HASH_MD5]  VARCHAR (50)     NULL,
    CONSTRAINT [PK_COUNTRYS_FLAGS_128X_COF128_ID] PRIMARY KEY CLUSTERED ([COF128_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_COUNTRYS__COUNTRYS_128X] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID])
);
GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_COUNTRYS_FLAGS_128X_FK]
    ON [dbo].[COUNTRYS_FLAGS_128X]([COU_ID] ASC);