CREATE TABLE [dbo].[COUNTRYS_FLAGS_64X] (
    [COF64_ID]             INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]               INT              NOT NULL,
    [COF64_FILE_BYTE]      VARBINARY (8000) NOT NULL,
    [COF64_FILE_NAME]      VARCHAR (100)    NOT NULL,
    [COF64_FILE_HASH_SHA1] VARCHAR (50)     NOT NULL,
    [COF64_FILE_HASH_MD5]  VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_COUNTRYS_FLAGS_64X_COF64_ID] PRIMARY KEY CLUSTERED ([COF64_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_COUNTRYS__COUNTRYS_64X] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID])
);
GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_COUNTRYS_FLAGS_64X_FK]
    ON [dbo].[COUNTRYS_FLAGS_64X]([COU_ID] ASC);