CREATE TABLE [dbo].[COUNTRYS_FLAGS_100X] (
    [COF100_ID]             INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]                INT              NOT NULL,
    [COF100_FILE_BYTE]      VARBINARY (MAX)  NOT NULL,
    [COF100_FILE_NAME]      VARCHAR (50)    NOT NULL,
    [COF100_FILE_HASH_SHA1] VARCHAR (50)     NOT NULL,
    [COF100_FILE_HASH_MD5]  VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_COUNTRYS_FLAGS_100X_COF100_ID] PRIMARY KEY CLUSTERED ([COF100_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_COUNTRYS__COUNTRYS_100X] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID])
);
GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_COUNTRYS_FLAGS_100X_FK]
    ON [dbo].[COUNTRYS_FLAGS_100X]([COU_ID] ASC);