CREATE TABLE [dbo].[CONTINENTS] (
    [CON_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [CON_NAME_EN] VARCHAR (100) NOT NULL,
    [CON_NAME_BR] VARCHAR (100) NOT NULL,
    [CON_CODE]    CHAR (2)      NOT NULL,
    CONSTRAINT [PK_CONTINENTS_CON_ID] PRIMARY KEY CLUSTERED ([CON_ID] ASC)
);
GO
CREATE UNIQUE NONCLUSTERED INDEX [CONTINENTS_UK]
    ON [dbo].[CONTINENTS]([CON_NAME_EN] ASC, [CON_NAME_BR] ASC, [CON_CODE] ASC);