CREATE TABLE [dbo].[COUNTRYS_FLAGS_32X] (
    [COF32_ID]             INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]               INT              NOT NULL,
    [COF32_FILE_BYTE]      VARBINARY (8000) NOT NULL,
    [COF32_FILE_NAME]      VARCHAR (50)    NOT NULL,
    [COF32_FILE_HASH_SHA1] VARCHAR (50)     NOT NULL,
    [COF32_FILE_HASH_MD5]  VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_COUNTRYS_FLAGS_32X_COF32_ID] PRIMARY KEY CLUSTERED ([COF32_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_COUNTRYS__COUNTRYS_32X] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID])
);
GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_COUNTRYS_FLAGS_32X_FK]
    ON [dbo].[COUNTRYS_FLAGS_32X]([COU_ID] ASC);