CREATE TABLE [dbo].[FEDERATIONS] (
    [FED_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [COU_ID]        INT           NOT NULL,
    [REG_ID]        INT           NOT NULL,
    [FED_NAME]      VARCHAR (100) NOT NULL,
    [FED_UF]        CHAR (2)      NOT NULL,
    [FED_IBGE_CODE] CHAR (2)      NOT NULL,
    CONSTRAINT [PK_FEDERATIONS_FED_ID] PRIMARY KEY CLUSTERED ([FED_ID] ASC),
    CONSTRAINT [FK_FEDERATI_COUNTRYS__COUNTRYS] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID]),
    CONSTRAINT [FK_FEDERATI_REGIONS_F_REGIONS] FOREIGN KEY ([REG_ID]) REFERENCES [dbo].[REGIONS] ([REG_ID])
);
GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_FEDERATIONS_FK]
    ON [dbo].[FEDERATIONS]([COU_ID] ASC);
GO
CREATE NONCLUSTERED INDEX [REGIONS_FOR_FEDERATIONS_FK]
    ON [dbo].[FEDERATIONS]([REG_ID] ASC);
GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDERATIONS_UK]
    ON [dbo].[FEDERATIONS]([FED_NAME] ASC, [FED_UF] ASC, [FED_IBGE_CODE] ASC);