CREATE TABLE [dbo].[COUNTRYS] (
    [COU_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [CON_ID]              INT           NOT NULL,
    [COU_NAME_EN]         VARCHAR (100) NOT NULL,
    [COU_NAME_BR]         VARCHAR (100) NOT NULL,
    [COU_ISO31661_ALPHA2] CHAR (2)      NOT NULL,
    [COU_ISO31661_ALPHA3] CHAR (3)      NOT NULL,
    [COU_ISO31661_NUMBER] VARCHAR (3)   NOT NULL,
    [COU_BACEN_CODE]      VARCHAR (5)   NOT NULL,
    [COU_LATITUDE]        VARCHAR (10)  NOT NULL,
    [COU_LONGITUDE]       VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_COUNTRYS_COU_ID] PRIMARY KEY CLUSTERED ([COU_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_CONTINENT_CONTINEN] FOREIGN KEY ([CON_ID]) REFERENCES [dbo].[CONTINENTS] ([CON_ID])
);










GO
CREATE NONCLUSTERED INDEX [CONTINENTS_FOR_COUNTRYS_FK]
    ON [dbo].[COUNTRYS]([CON_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [COUNTRYS_UK]
    ON [dbo].[COUNTRYS]([COU_NAME_EN] ASC, [COU_NAME_BR] ASC, [COU_ISO31661_ALPHA2] ASC, [COU_ISO31661_ALPHA3] ASC, [COU_ISO31661_NUMBER] ASC, [COU_BACEN_CODE] ASC);

