CREATE TABLE [dbo].[CITYS] (
    [CIT_ID]             INT           IDENTITY (1, 1) NOT NULL,
    [FED_ID]             INT           NOT NULL,
    [CIT_NAME]           VARCHAR (100) NOT NULL,
    [CID_IBGE_CODE]      VARCHAR (10)  NOT NULL,
    [CIT_IBGE_LONGITUDE] VARCHAR (10)  NOT NULL,
    [CIT_IBGE_LATITUDE]  VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_CITYS_CIT_ID] PRIMARY KEY CLUSTERED ([CIT_ID] ASC),
    CONSTRAINT [FK_CITYS_FERERATIO_FEDERATI] FOREIGN KEY ([FED_ID]) REFERENCES [dbo].[FEDERATIONS] ([FED_ID])
);








GO
CREATE NONCLUSTERED INDEX [FERERATIONS_FOR_CITYS_FK]
    ON [dbo].[CITYS]([FED_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [CITYS_UK]
    ON [dbo].[CITYS]([CIT_NAME] ASC, [CID_IBGE_CODE] ASC);

