CREATE TABLE [dbo].[STATES_FLAG] (
    [STF_ID]   INT              IDENTITY (1, 1) NOT NULL,
    [STA_ID]   INT              NOT NULL,
    [STF_FLAG] VARBINARY (8000) NOT NULL,
    CONSTRAINT [PK_STATES_FLAG] PRIMARY KEY CLUSTERED ([STF_ID] ASC),
    CONSTRAINT [FK_STATES_F_STATES_FO_STATES] FOREIGN KEY ([STA_ID]) REFERENCES [dbo].[STATES] ([STA_ID])
);


GO
CREATE NONCLUSTERED INDEX [STATE_FOR_FLAGSTATE_FK]
    ON [dbo].[STATES_FLAG]([STA_ID] ASC);

