CREATE TABLE [dbo].[TBCOUNTRYSTATE] (
    [CST_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [COU_ID]   INT           NOT NULL,
    [CST_NAME] VARCHAR (100) NOT NULL,
    [CST_UF]   VARCHAR (2)   NOT NULL,
    CONSTRAINT [PK_TBCOUNTRYSTATE] PRIMARY KEY CLUSTERED ([CST_ID] ASC),
    CONSTRAINT [FK_TBCOUNTR_COUNTRY_S_TBCOUNTR] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[TBCOUNTRY] ([COU_ID])
);




GO
CREATE NONCLUSTERED INDEX [COUNTRY_STATES_FK]
    ON [dbo].[TBCOUNTRYSTATE]([COU_ID] ASC);

