CREATE TABLE [dbo].[STATES] (
    [STA_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [COU_ID]   INT           NOT NULL,
    [STA_UF]   CHAR (2)      NOT NULL,
    [STA_NAME] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_STATES] PRIMARY KEY CLUSTERED ([STA_ID] ASC),
    CONSTRAINT [FK_STATES_COUNTRY_F_COUNTRY] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRY] ([COU_ID])
);




GO
CREATE NONCLUSTERED INDEX [COUNTRY_FOR_STATE_FK]
    ON [dbo].[STATES]([COU_ID] ASC);

