CREATE TABLE [dbo].[CITY] (
    [CIT_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [STA_ID]   INT           NOT NULL,
    [CIT_NAME] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED ([CIT_ID] ASC),
    CONSTRAINT [FK_CITY_STATES_FO_STATES] FOREIGN KEY ([STA_ID]) REFERENCES [dbo].[STATES] ([STA_ID])
);


GO
CREATE NONCLUSTERED INDEX [STATE_FOR_CITY_FK]
    ON [dbo].[CITY]([STA_ID] ASC);

