CREATE TABLE [dbo].[TBCOUNTRY] (
    [COU_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [COU_NOME]            VARCHAR (100) NOT NULL,
    [COU_NAME]            VARCHAR (100) NOT NULL,
    [COU_NOMBRE]          VARCHAR (100) NOT NULL,
    [COU_ISO31661NUMERIC] INT           NOT NULL,
    [COU_ISO31661ALPHA2]  INT           NOT NULL,
    [COU_ISO31661ALPHA3]  INT           NOT NULL,
    CONSTRAINT [PK_TBCOUNTRY] PRIMARY KEY CLUSTERED ([COU_ID] ASC)
);



