CREATE TABLE [dbo].[COUNTRY_FLAG] (
    [COF_ID]   INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]   INT              NOT NULL,
    [COF_FLAG] VARBINARY (8000) NOT NULL,
    CONSTRAINT [PK_COUNTRY_FLAG] PRIMARY KEY CLUSTERED ([COF_ID] ASC),
    CONSTRAINT [FK_COUNTRY__COUNTRYFL_COUNTRY] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRY] ([COU_ID])
);


GO
CREATE NONCLUSTERED INDEX [COUNTRYFLAG_FK]
    ON [dbo].[COUNTRY_FLAG]([COU_ID] ASC);

