CREATE TABLE [dbo].[REGIONS] (
    [REG_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [REG_NAME] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_REGIONS_REG_ID] PRIMARY KEY CLUSTERED ([REG_ID] ASC)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [REGIONS_UK]
    ON [dbo].[REGIONS]([REG_NAME] ASC);

