CREATE TABLE [dbo].[COUNTRY_DESCRIPTION] (
    [CDE_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [COU_ID]          INT           NOT NULL,
    [CDE_DESCRIPTION] VARCHAR (999) NOT NULL,
    CONSTRAINT [PK_COUNTRY_DESCRIPTION] PRIMARY KEY CLUSTERED ([CDE_ID] ASC),
    CONSTRAINT [FK_COUNTRY__COUNTRYDE_COUNTRY] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRY] ([COU_ID])
);


GO
CREATE NONCLUSTERED INDEX [COUNTRYDESCRIPTION_FK]
    ON [dbo].[COUNTRY_DESCRIPTION]([COU_ID] ASC);

