CREATE TABLE [dbo].[COUNTRYS_FLAGS_24X] (
    [COF24_ID]             INT              IDENTITY (1, 1) NOT NULL,
    [COU_ID]               INT              NOT NULL,
    [COF24_FILE_BYTE]      VARBINARY (8000) NOT NULL,
    [COF24_FILE_NAME]      VARCHAR (100)    NOT NULL,
    [COF24_FILE_HASH_SHA1] VARCHAR (50)     NOT NULL,
    [COF24_FILE_HASH_MD5]  VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_COUNTRYS_FLAGS_24X_COF24_ID] PRIMARY KEY CLUSTERED ([COF24_ID] ASC),
    CONSTRAINT [FK_COUNTRYS_COUNTRYS__COUNTRYS_24X] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRYS] ([COU_ID])
);




GO
CREATE NONCLUSTERED INDEX [COUNTRYS_FOR_COUNTRYS_FLAGS_24X24_FK]
    ON [dbo].[COUNTRYS_FLAGS_24X]([COU_ID] ASC);

