CREATE TABLE [dbo].[COUNTRY_CURRENCY] (
    [CCU_ID] INT IDENTITY (1, 1) NOT NULL,
    [COU_ID] INT NOT NULL,
    [CUR_ID] INT NOT NULL,
    CONSTRAINT [PK_COUNTRY_CURRENCY] PRIMARY KEY CLUSTERED ([CCU_ID] ASC),
    CONSTRAINT [FK_COUNTRY__COUNTRYCU_COUNTRY] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRY] ([COU_ID]),
    CONSTRAINT [FK_COUNTRY__CURRENCYC_CURRENCY] FOREIGN KEY ([CUR_ID]) REFERENCES [dbo].[CURRENCY] ([CUR_ID])
);


GO
CREATE NONCLUSTERED INDEX [CURRENCYCOUNTRY_FK]
    ON [dbo].[COUNTRY_CURRENCY]([CUR_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [COUNTRYCURRENCY_FK]
    ON [dbo].[COUNTRY_CURRENCY]([COU_ID] ASC);

