CREATE TABLE [dbo].[CONTINENT] (
    [CON_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [CON_NAME_EN] VARCHAR (100) NOT NULL,
    [CON_NAME_BR] VARCHAR (100) NOT NULL,
    [CON_CODE]    CHAR (2)      NOT NULL,
    CONSTRAINT [PK_CONTINENT] PRIMARY KEY CLUSTERED ([CON_ID] ASC),
    CONSTRAINT [CKC_CON_ID_CONTINEN] CHECK ([CON_ID]>=(1) AND [CON_ID]<=(7))
);

