CREATE TABLE [dbo].[CITY_FLAG] (
    [CIF_ID]   INT              IDENTITY (1, 1) NOT NULL,
    [CIT_ID]   INT              NOT NULL,
    [CIF_FLAG] VARBINARY (8000) NOT NULL,
    CONSTRAINT [PK_CITY_FLAG] PRIMARY KEY CLUSTERED ([CIF_ID] ASC),
    CONSTRAINT [FK_CITY_FLA_CITY_FOR__CITY] FOREIGN KEY ([CIT_ID]) REFERENCES [dbo].[CITY] ([CIT_ID])
);


GO
CREATE NONCLUSTERED INDEX [CITY_FOR_FLAGCITY_FK]
    ON [dbo].[CITY_FLAG]([CIT_ID] ASC);

