CREATE TABLE [dbo].[COUNTRY] (
    [COU_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [CON_ID]              INT           NOT NULL,
    [COU_NAME_EN]         VARCHAR (100) NOT NULL,
    [COU_NAME_BR]         VARCHAR (100) NOT NULL,
    [COU_ISO31661_ALPHA2] CHAR (2)      NOT NULL,
    [COU_ISO31661_ALPHA3] CHAR (3)      NOT NULL,
    [COU_ISO31661_NUMBER] INT           NOT NULL,
    CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED ([COU_ID] ASC),
    CONSTRAINT [CKC_CON_ID_COUNTRY] CHECK ([CON_ID]>=(1) AND [CON_ID]<=(7)),
    CONSTRAINT [FK_COUNTRY_CONTINENT_CONTINEN] FOREIGN KEY ([CON_ID]) REFERENCES [dbo].[CONTINENT] ([CON_ID])
);








GO
CREATE NONCLUSTERED INDEX [CONTINENTFORCOUNTRY_FK]
    ON [dbo].[COUNTRY]([CON_ID] ASC);

