CREATE TABLE [dbo].[TBSTATECITY] (
    [SCI_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [CST_ID]   INT           NOT NULL,
    [SCI_NAME] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBSTATECITY] PRIMARY KEY CLUSTERED ([SCI_ID] ASC),
    CONSTRAINT [FK_TBSTATEC_STATE_CIT_TBCOUNTR] FOREIGN KEY ([CST_ID]) REFERENCES [dbo].[TBCOUNTRYSTATE] ([CST_ID])
);




GO
CREATE NONCLUSTERED INDEX [STATE_CITY_FK]
    ON [dbo].[TBSTATECITY]([CST_ID] ASC);

