CREATE TABLE [dbo].[COUNTRY_CAPITAL] (
    [CCA_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [COU_ID]   INT           NOT NULL,
    [CCA_NAME] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_COUNTRY_CAPITAL] PRIMARY KEY CLUSTERED ([CCA_ID] ASC),
    CONSTRAINT [FK_COUNTRY__COUNTRYCA_COUNTRY] FOREIGN KEY ([COU_ID]) REFERENCES [dbo].[COUNTRY] ([COU_ID])
);


GO
CREATE NONCLUSTERED INDEX [COUNTRYCAPITAL_FK]
    ON [dbo].[COUNTRY_CAPITAL]([COU_ID] ASC);

